# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Batman <- function(X, Y, probs, num_cat, num_tree, scale_lambda, shape_lambda_0, rate_lambda_0, scale_kappa, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_burn, num_thin, num_save, X_test, Y_test) {
    .Call(`_Batman_Batman`, X, Y, probs, num_cat, num_tree, scale_lambda, shape_lambda_0, rate_lambda_0, scale_kappa, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_burn, num_thin, num_save, X_test, Y_test)
}

CLogLogOrdinalBart <- function(X, Y, num_levels, X_test, probs, num_trees, scale_lambda, alpha_gamma, beta_gamma, gamma_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_CLogLogOrdinalBart`, X, Y, num_levels, X_test, probs, num_trees, scale_lambda, alpha_gamma, beta_gamma, gamma_0, num_burn, num_thin, num_save)
}

CoxBart <- function(X, Y, delta, order, L, U, probs, X_test, num_trees, scale_lambda, num_burn, num_thin, num_save) {
    .Call(`_Batman_CoxBart`, X, Y, delta, order, L, U, probs, X_test, num_trees, scale_lambda, num_burn, num_thin, num_save)
}

CoxNPHBart <- function(X, Y, delta, bin_to_obs_list, obs_to_bin, time_grid, bin_width, base_haz_init, probs, X_test, num_trees, scale_lambda, do_rel_surv, pop_haz_, num_burn, num_thin, num_save) {
    .Call(`_Batman_CoxNPHBart`, X, Y, delta, bin_to_obs_list, obs_to_bin, time_grid, bin_width, base_haz_init, probs, X_test, num_trees, scale_lambda, do_rel_surv, pop_haz_, num_burn, num_thin, num_save)
}

CoxPEBart <- function(X, Y, delta, bin_to_obs_list, obs_to_bin, time_grid, bin_width, base_haz_init, probs, X_test, num_trees, scale_lambda, do_rel_surv, pop_haz_, num_burn, num_thin, num_save) {
    .Call(`_Batman_CoxPEBart`, X, Y, delta, bin_to_obs_list, obs_to_bin, time_grid, bin_width, base_haz_init, probs, X_test, num_trees, scale_lambda, do_rel_surv, pop_haz_, num_burn, num_thin, num_save)
}

GammaRegBart <- function(X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_GammaRegBart`, X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

MLogitBart <- function(X, Y, probs, num_cat, num_trees, scale_lambda, shape_lambda_0, rate_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_MLogitBart`, X, Y, probs, num_cat, num_trees, scale_lambda, shape_lambda_0, rate_lambda_0, num_burn, num_thin, num_save)
}

PoisBart <- function(X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_PoisBart`, X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

QBinomBart <- function(X, Y, n, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_QBinomBart`, X, Y, n, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

QGammaBart <- function(X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_QGammaBart`, X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

QMultinomBart <- function(X, Y, n, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_QMultinomBart`, X, Y, n, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

QNBBart <- function(X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_QNBBart`, X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

QPoisBart <- function(X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_QPoisBart`, X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

QPowerBart <- function(X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_QPowerBart`, X, Y, X_test, probs, num_trees, scale_lambda, scale_lambda_0, num_burn, num_thin, num_save)
}

RVarBart <- function(X, Y, probs, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_trees, num_burn, num_thin, num_save, update_scale_log_tau, update_s) {
    .Call(`_Batman_RVarBart`, X, Y, probs, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_trees, num_burn, num_thin, num_save, update_scale_log_tau, update_s)
}

RegBart <- function(X, Y, X_test, probs, num_trees, scale_sigma, scale_sigma_mu, num_burn, num_thin, num_save) {
    .Call(`_Batman_RegBart`, X, Y, X_test, probs, num_trees, scale_sigma, scale_sigma_mu, num_burn, num_thin, num_save)
}

doit <- function() {
    invisible(.Call(`_Batman_doit`))
}

WeibAugment <- function(failure_times, X, rate, shape) {
    .Call(`_Batman_WeibAugment`, failure_times, X, rate, shape)
}

VarBart <- function(X, Y, probs, scale_kappa, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_trees, num_burn, num_thin, num_save) {
    .Call(`_Batman_VarBart`, X, Y, probs, scale_kappa, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_trees, num_burn, num_thin, num_save)
}

VarLogitBart <- function(X_logit, Y_logit, X_var, Y_var, probs, num_cat, num_trees, scale_lambda, shape_lambda_0, rate_lambda_0, scale_kappa, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_burn, num_thin, num_save) {
    .Call(`_Batman_VarLogitBart`, X_logit, Y_logit, X_var, Y_var, probs, num_cat, num_trees, scale_lambda, shape_lambda_0, rate_lambda_0, scale_kappa, sigma_scale_log_tau, shape_tau_0, rate_tau_0, num_burn, num_thin, num_save)
}

WeibBart <- function(X, Y, W, idx, probs, num_trees, scale_lambda, shape_lambda_0, rate_lambda_0, weibull_power, do_ard, update_alpha, update_scale, num_burn, num_thin, num_save) {
    .Call(`_Batman_WeibBart`, X, Y, W, idx, probs, num_trees, scale_lambda, shape_lambda_0, rate_lambda_0, weibull_power, do_ard, update_alpha, update_scale, num_burn, num_thin, num_save)
}

rlgam <- function(shape) {
    .Call(`_Batman_rlgam`, shape)
}

gaussian_gaussian_marginal_loglik <- function(n, sum_y, sum_y_sq, prec_y, prec_mu) {
    .Call(`_Batman_gaussian_gaussian_marginal_loglik`, n, sum_y, sum_y_sq, prec_y, prec_mu)
}

trigamma_inverse <- function(x) {
    .Call(`_Batman_trigamma_inverse`, x)
}

gamma_gamma_shape_update <- function(tau, mu, alpha, beta) {
    .Call(`_Batman_gamma_gamma_shape_update`, tau, mu, alpha, beta)
}

convertListToVector <- function(list) {
    .Call(`_Batman_convertListToVector`, list)
}

rcpparma_hello_world <- function() {
    .Call(`_Batman_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_Batman_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_Batman_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_Batman_rcpparma_bothproducts`, x)
}

